Concatenamos los CSV Y_ulta_beauty y G_ulta_beauty

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [17]:
Y_ulta_beauty = pd.read_csv('..\datasets\csv\Y_ulta_beauty.csv')
G_ulta_beauty = pd.read_csv('..\datasets\csv\G_ulta_bauty.csv')
G_ulta_beauty.drop('Unnamed: 0', axis=1, inplace=True)

In [18]:
ulta_beauty = pd.concat([Y_ulta_beauty, G_ulta_beauty])

In [19]:
ulta_beauty

,user_id,business_id,stars,text,year,state,latitude,longitude,source,month
0,dKN5pfsZYMyNXw6QekuYrg,idP674ti6a8yg8z2xFcCgA,1.0,I recently bought $50 worth of hair products I...,2017,AZ,39.987189,-75.403201,Y,9
1,OxPwTirxr6jsthULWBAuZg,idP674ti6a8yg8z2xFcCgA,1.0,Based on other reviews I see I am not the only...,2018,AZ,39.987189,-75.403201,Y,6
2,nAURZM3uxMR1pVpKIav-Iw,idP674ti6a8yg8z2xFcCgA,1.0,I specifically came to this store because it w...,2017,AZ,39.987189,-75.403201,Y,1
3,qYsHVItNC1_WnJGBIx5kXA,idP674ti6a8yg8z2xFcCgA,5.0,Received a great haircut from Jess.\n\nI neede...,2017,AZ,39.987189,-75.403201,Y,2
4,JpE6JdtbkOqXUElu2q28Og,idP674ti6a8yg8z2xFcCgA,1.0,Agree with the other reviews that are unhappy ...,2018,AZ,39.987189,-75.403201,Y,3
...,...,...,...,...,...,...,...,...,...,...
17183,112097075757251100672.0,0x533495e641aa6e71:0xcb788f90b8c056ae,5.0,NaN,2021,WY,44.274553,-105.498059,G,2
17184,109914503708150087680.0,0x533495e641aa6e71:0xcb788f90b8c056ae,5.0,NaN,2020,WY,44.274553,-105.498059,G,9
17185,100016262725100437504.0,0x533495e641aa6e71:0xcb788f90b8c056ae,5.0,NaN,2021,WY,44.274553,-105.498059,G,6
17186,112885620950040674304.0,0x533495e641aa6e71:0xcb788f90b8c056ae,5.0,NaN,2021,WY,44.274553,-105.498059,G,6
17187,104466637532735275008.0,0x533495e641aa6e71:0xcb788f90b8c056ae,5.0,NaN,2021,WY,44.274553,-105.498059,G,2

Estandarizamos el business_id para evitar que se dupliquen en las bases de google y yelp ya que en cada fuente de informacion el id es distinto

In [32]:
filtered_df = ulta_beauty[ulta_beauty['latitude'] == 39.987189]